
package ctrl;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyWebservice", targetNamespace = "http://ctrl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyWebservice {


    /**
     * 
     * @return
     *     returns ctrl.Buch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "holeBuch", targetNamespace = "http://ctrl/", className = "ctrl.HoleBuch")
    @ResponseWrapper(localName = "holeBuchResponse", targetNamespace = "http://ctrl/", className = "ctrl.HoleBuchResponse")
    public Buch holeBuch();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "calculate", targetNamespace = "http://ctrl/", className = "ctrl.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://ctrl/", className = "ctrl.CalculateResponse")
    public void calculate();

    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://ctrl/", className = "ctrl.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://ctrl/", className = "ctrl.HelloResponse")
    public String hello(
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "longTimeCalculate", targetNamespace = "http://ctrl/", className = "ctrl.LongTimeCalculate")
    public void longTimeCalculate();

}
